# Generated by Django 5.0.4 on 2024-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_apporved',
            field=models.BooleanField(default=True),
        ),
    ]
