# Generated by Django 5.0.4 on 2024-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
