# Generated by Django 5.0.4 on 2024-06-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_car_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
    ]
