# Generated by Django 5.0.4 on 2024-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_car_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='images/')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('image1', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='images/')),
                ('add_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'book table',
            },
        ),
    ]
