# Generated by Django 5.0.6 on 2024-06-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_book_email_remove_book_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='img',
        ),
    ]
