# Generated by Django 5.0.6 on 2024-06-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_file_book_image_remove_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
