# Generated by Django 5.0.6 on 2024-07-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
